=== vlastachu/xml-calculator/src/test/resources/Calculator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:attribute name="OperationType">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="SUB"/>
                <xs:enumeration value="SUM"/>
                <xs:enumeration value="MUL"/>
                <xs:enumeration value="DIV"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    <xs:complexType name="term">
        <xs:choice>
            <xs:sequence>
                <xs:element name="arg" type="xs:nonNegativeInteger" minOccurs="2" maxOccurs="2"/>
            </xs:sequence>
            <xs:sequence>
                <xs:element name="arg1" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
                <xs:element name="operation1" type="term" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:sequence>
                <xs:element name="operation2" type="term" minOccurs="1" maxOccurs="1"/>
                <xs:element name="arg2" type="xs:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:sequence>
                <xs:element name="operation" type="term" minOccurs="2" maxOccurs="2"/>
            </xs:sequence>
        </xs:choice>
        <xs:attribute ref="OperationType"/>
    </xs:complexType>

    <xs:element name="simpleCalculator">
        <xs:complexType>
            <xs:choice maxOccurs="1">
                <xs:element name="expressions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="expression" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="operation" type="term"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="expressionResults">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="expressionResult" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="result" type="xs:double" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>

    </xs:element>


</xs:schema>

=== vlastachu/xml-calculator/src/main/resources/sampleTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<simpleCalculator xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Calculator.xsd">
    <expressions>
        <expression>
            <operation OperationType="MUL">
                <operation OperationType="SUB">
                    <operation OperationType="SUM">
                        <arg>2</arg>
                        <arg>4</arg>
                    </operation>
                    <operation OperationType="DIV">
                        <arg>1</arg>
                        <arg>4</arg>
                    </operation>
                </operation>
                <operation OperationType="SUB">
                    <operation OperationType="SUM">
                        <arg>12</arg>
                        <arg>55</arg>
                    </operation>
                    <operation OperationType="MUL">
                        <arg>123</arg>
                        <arg>4</arg>
                    </operation>
                </operation>
            </operation>
        </expression>

        <expression>
            <operation OperationType="SUB">
                <operation OperationType="MUL">
                    <operation OperationType="DIV">
                        <arg>211</arg>
                        <arg>114</arg>
                    </operation>
                    <operation OperationType="DIV">
                        <arg>13</arg>
                        <arg>41</arg>
                    </operation>
                </operation>
                <operation OperationType="SUB">
                    <operation OperationType="SUM">
                        <arg>123</arg>
                        <arg>1235</arg>
                    </operation>
                    <operation OperationType="MUL">
                        <arg>55</arg>
                        <arg>1111</arg>
                    </operation>
                </operation>
            </operation>
        </expression>
    </expressions>
</simpleCalculator>
